title: Weiping Yan
first_name: Weiping
last_name: Yan

email: vipinapple986@gmail.com

description: >
  AI for Science | Foundation Models | Analog Circuit Design

baseurl: ""
url: "https://appleweiping.github.io"

theme: null

markdown: kramdown

navbar:
  - title: About
    url: /
  - title: Projects
    url: /projects/
  - title: CV
    url: /cv/

github_username: appleweiping
linkedin_username: weiping-yan-b62567383

enable_darkmode: true