import type { CabinetLocale } from "./types";

const copy = {
  en: {
    title: "Cabinet of Inquiry",
    subtitle: "A navigable record of public work",
    collection: "Collection",
    galleries: "Galleries",
    galleryMap: "Gallery map",
    searchLabel: "Search every exhibit",
    searchPlaceholder: "Project, topic, or language",
    searchResults: "Search results",
    noSearchResults: "No exhibits match this search.",
    loading: "Preparing the galleries…",
    lobbyEyebrow: "Central rotunda",
    lobbyTitle: "Enter the Cabinet of Inquiry",
    lobbyBody: "Follow the guided route through the current gallery, or use the catalogue to move directly to an exhibit.",
    newAcquisitions: "New Acquisitions",
    noNewAcquisitions: "No public repositories are awaiting curatorial review.",
    startTour: "Begin guided tour",
    guided: "Guided tour",
    free: "Free exploration",
    enterFree: "Explore with WASD",
    returnGuided: "Return to guided tour",
    pointerHint: "Click the gallery to capture the mouse. Use WASD to move and Esc to release.",
    mobileHint: "Touch devices use the guided route and direct exhibit navigation.",
    currentGallery: "Current gallery",
    exhibitCatalogue: "Exhibit catalogue",
    exhibits: "exhibits",
    openExhibit: "Open exhibit",
    fallbackTitle: "The accessible collection",
    fallbackBody: "This device is using the complete two-dimensional collection for comfort and reliability.",
    fallbackWebgl: "WebGL is unavailable.",
    fallbackMotion: "Reduced motion is enabled.",
    fallbackData: "Data Saver is enabled.",
    fallbackPower: "A low-power device was detected.",
    fallbackContext: "The 3D graphics context was interrupted.",
    try3d: "Try the 3D galleries",
    view2d: "Use 2D collection",
    filterGallery: "Filter by gallery",
    allGalleries: "All galleries",
    noCollectionResults: "No collection records match these filters.",
    details: "Exhibit details",
    close: "Close exhibit",
    repository: "Source repository",
    contribution: "Contribution",
    status: "Status",
    updated: "Last updated",
    recordType: "Record type",
    demo: "Demonstration",
    demoEmbedIntro: "This verified interactive demonstration loads only when requested.",
    loadDemo: "Load interactive demo",
    openDemo: "Open demo in a new tab",
    demoExternal: "The verified demonstration opens on its original site.",
    demoMedia: "Recorded project evidence",
    demoNone: "No public demonstration is currently available. The source record remains accessible.",
    demoUnavailable: "The demonstration metadata is incomplete; use the source repository instead.",
    pending: "Awaiting bilingual curation",
    interfaceStatus: "Gallery status",
  },
  zh: {
    title: "格物馆",
    subtitle: "可漫游的公开工作档案",
    collection: "馆藏",
    galleries: "分馆",
    galleryMap: "分馆地图",
    searchLabel: "搜索全部展品",
    searchPlaceholder: "项目、主题或语言",
    searchResults: "搜索结果",
    noSearchResults: "没有符合搜索条件的展品。",
    loading: "正在布置展厅……",
    lobbyEyebrow: "中央前厅",
    lobbyTitle: "进入格物馆",
    lobbyBody: "沿导览路线参观当前分馆，或通过馆藏目录直接抵达任一展品。",
    newAcquisitions: "新近入藏",
    noNewAcquisitions: "目前没有等待策展复核的公开仓库。",
    startTour: "开始导览",
    guided: "导览模式",
    free: "自由漫游",
    enterFree: "使用 WASD 漫游",
    returnGuided: "返回导览",
    pointerHint: "点击展厅以锁定鼠标，使用 WASD 移动，按 Esc 释放。",
    mobileHint: "触屏设备使用导览路线与展品直达功能。",
    currentGallery: "当前分馆",
    exhibitCatalogue: "展品目录",
    exhibits: "件展品",
    openExhibit: "打开展品",
    fallbackTitle: "无障碍二维馆藏",
    fallbackBody: "为保证舒适度与可靠性，本设备正在使用完整二维馆藏。",
    fallbackWebgl: "当前环境不支持 WebGL。",
    fallbackMotion: "系统已启用减少动态效果。",
    fallbackData: "系统已启用节省流量。",
    fallbackPower: "检测到低功耗设备。",
    fallbackContext: "三维图形上下文已中断。",
    try3d: "仍然尝试三维展厅",
    view2d: "使用二维馆藏",
    filterGallery: "按分馆筛选",
    allGalleries: "全部分馆",
    noCollectionResults: "没有符合当前筛选条件的馆藏记录。",
    details: "展品详情",
    close: "关闭展品",
    repository: "源码仓库",
    contribution: "个人贡献",
    status: "状态",
    updated: "最近更新",
    recordType: "记录类型",
    demo: "演示证据",
    demoEmbedIntro: "该已验证的交互演示仅在你主动请求后加载。",
    loadDemo: "加载交互演示",
    openDemo: "在新标签页打开演示",
    demoExternal: "已验证的演示将在原始站点打开。",
    demoMedia: "项目实证材料",
    demoNone: "目前没有公开 Demo，源码记录仍可访问。",
    demoUnavailable: "演示元数据不完整，请改用源码仓库。",
    pending: "待完成双语策展",
    interfaceStatus: "展厅状态",
  },
} as const;

export function getCabinetCopy(locale: CabinetLocale) {
  return copy[locale];
}
